/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GestionDoubleChainage;

/**
 *
 * @author Guillaume
 */
public class GestionDoubleChainage extends javax.swing.JFrame {

    /**
     * Creates new form GestionDoubleChainage
     */
    public GestionDoubleChainage() {
        initComponents();
        listeString = new java.util.LinkedList<>(); //On initialise listeString.
        saisieTexte.selectAll();
        saisieTexte.requestFocus();
        setLocation(250,150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        saisieTexte = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        afficheListe = new javax.swing.JTextField();
        btnAjoutDeb = new javax.swing.JButton();
        btnAjoutFin = new javax.swing.JButton();
        btnRetireDeb = new javax.swing.JButton();
        btnRetireFin = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnFin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de double chainage");

        jLabel1.setText("Valeur :");

        jLabel2.setText("Liste Chaînée :");

        afficheListe.setEditable(false);

        btnAjoutDeb.setText("Insérer Début");
        btnAjoutDeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutDebutAction(evt);
            }
        });

        btnAjoutFin.setText("Insérer Fin");
        btnAjoutFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajoutFinAction(evt);
            }
        });

        btnRetireDeb.setText("Retirer Début");
        btnRetireDeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retireDebutAction(evt);
            }
        });

        btnRetireFin.setText("Retirer Fin");
        btnRetireFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retireFinAction(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAction(evt);
            }
        });

        btnFin.setText("Fin");
        btnFin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finAction(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(saisieTexte, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(afficheListe))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAjoutDeb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAjoutFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRetireDeb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRetireFin)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(saisieTexte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(afficheListe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjoutFin)
                    .addComponent(btnAjoutDeb)
                    .addComponent(btnRetireDeb)
                    .addComponent(btnRetireFin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClear)
                    .addComponent(btnFin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ajoutFinAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutFinAction
        // On ajoute l'élément saisie à la fin de listeString.
        // Si rien n'est saisie on informe l'utilisateur et on insert rien.
        if(saisieTexte.getText().equals("")){
            javax.swing.JOptionPane.showMessageDialog(this,"Rien à insérer","Information",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }else{
            listeString.addLast(saisieTexte.getText());
            afficheListe.setText(listeString.toString());
            saisieTexte.setText("");
            saisieTexte.requestFocus();
        }
    }//GEN-LAST:event_ajoutFinAction

    private void ajoutDebutAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajoutDebutAction
        // On ajoute l'élément saisie au début de listeString.
        // Si rien n'est saisie on informe l'utilisateur et on insert rien.
        if(saisieTexte.getText().equals("")){
            javax.swing.JOptionPane.showMessageDialog(this,"Rien à insérer","Information",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }else{
            listeString.addFirst(saisieTexte.getText());
            afficheListe.setText(listeString.toString());
            saisieTexte.setText("");
            saisieTexte.requestFocus();
        }
    }//GEN-LAST:event_ajoutDebutAction

    private void retireDebutAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retireDebutAction
        // On retire l'élément au début de listeString.
        // Si la listeString est vide on informe de l'erreur à l'utilisateur;
        try{
            listeString.removeFirst();
            if((listeString.toString()).equals("[]")){
                afficheListe.setText("");
                saisieTexte.requestFocus();
            } else{
                afficheListe.setText(listeString.toString());
                saisieTexte.requestFocus();
            }
        }catch( java.util.NoSuchElementException e){
            javax.swing.JOptionPane.showMessageDialog(this,"Rien à retirer","Erreur",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_retireDebutAction

    private void retireFinAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retireFinAction
        // On retire l'élément à la fin de listeString.
        // Si la listeString est vide on informe de l'erreur à l'utilisateur;
        try{
            listeString.removeLast();
            if((listeString.toString()).equals("[]")){
                afficheListe.setText("");
                saisieTexte.requestFocus();
            } else{
                afficheListe.setText(listeString.toString());
                saisieTexte.requestFocus();
            }
        }catch(java.util.NoSuchElementException e){
             javax.swing.JOptionPane.showMessageDialog(this,"Rien à retirer","Erreur",javax.swing.JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_retireFinAction

    private void finAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finAction
        // Fonction qui ferme l'application.
        dispose();
        System.exit(0);
    }//GEN-LAST:event_finAction

    private void clearAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAction
        // Ici on nettoie l'affichage et la liste chaînée.
        listeString.clear();
        if((listeString.toString()).equals("[]")){
            afficheListe.setText("");
            saisieTexte.requestFocus();
            javax.swing.JOptionPane.showMessageDialog(this,"La liste est vidée.","Information",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_clearAction

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionDoubleChainage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionDoubleChainage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionDoubleChainage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionDoubleChainage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionDoubleChainage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField afficheListe;
    private javax.swing.JButton btnAjoutDeb;
    private javax.swing.JButton btnAjoutFin;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnFin;
    private javax.swing.JButton btnRetireDeb;
    private javax.swing.JButton btnRetireFin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField saisieTexte;
    // End of variables declaration//GEN-END:variables
    java.util.LinkedList<String> listeString; //On déclare la linkedList listeString pour stocker nos élments.
}
