/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package choixconfiguration;

/**
 *
 * @author Guillaume
 */
public class ChoixConfiguration extends javax.swing.JFrame {

    /**
     * Creates new form ChoixConfiguration
     */
    public ChoixConfiguration() {
        initComponents();
        setLocation(250,100);
        
        //On fait des tableaux d'éléments pour chaque option.
        listRam = new String[]{
            "2G","4G","6G","8G"
        };
        
        listDD = new String[]{
            "200G","400G","600G"
        };
        
        listEcran = new String[]{
            "15''","18''","23''"
        };
                
        listLecteur = new String[]{
            "IHAS124-14","DRW-24F1MT","BC-12D2"
        };   
        
        listGraveur = new String[]{
            "SDRW 08","BW SD1","BW-SD1HT"
        };
        
        //Puis on ajoute les éléments aux combo-box afin de pouvoir les choisirs.
        for (String ram : listRam)choixRam.addItem(ram);
        for (String dd : listDD)choixDD.addItem(dd);
        for (String ecran : listEcran)choixEcran.addItem(ecran);
        for (String lecteur : listLecteur)choixLecteur.addItem(lecteur);
        for (String graveur : listGraveur)choixGraveur.addItem(graveur);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        CPU = new javax.swing.JPanel();
        IntelPentium = new javax.swing.JRadioButton();
        AMD = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonLancer = new javax.swing.JButton();
        choixRam = new javax.swing.JComboBox<>();
        choixDD = new javax.swing.JComboBox<>();
        choixEcran = new javax.swing.JComboBox<>();
        choixLecteur = new javax.swing.JComboBox<>();
        choixGraveur = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choix de Configuration");

        CPU.setBorder(javax.swing.BorderFactory.createTitledBorder("CPU"));
        CPU.setName(""); // NOI18N

        buttonGroup1.add(IntelPentium);
        IntelPentium.setText("INTEL_Pentium");
        IntelPentium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Intel(evt);
            }
        });

        buttonGroup1.add(AMD);
        AMD.setText("AMD");
        AMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AMD(evt);
            }
        });

        javax.swing.GroupLayout CPULayout = new javax.swing.GroupLayout(CPU);
        CPU.setLayout(CPULayout);
        CPULayout.setHorizontalGroup(
            CPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CPULayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(IntelPentium)
                .addGap(151, 151, 151)
                .addComponent(AMD, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        CPULayout.setVerticalGroup(
            CPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CPULayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CPULayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IntelPentium)
                    .addComponent(AMD))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setText("RAM");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setText("Disque Dur");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setText("Ecran");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setText("Lecteur");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setText("Graveur");

        buttonLancer.setText("Lancer");
        buttonLancer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lancer(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(133, 133, 133)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(choixDD, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(choixRam, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(choixEcran, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(choixLecteur, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(choixGraveur, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(buttonLancer, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(CPU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(choixRam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(choixDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(choixEcran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(choixLecteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(choixGraveur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLancer)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        CPU.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Lancer(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lancer
        // On affiche dans une fenêtre de dialogue les informations de la configuration.
        
        //On prépare le String à afficher.
        if(cpu==null)cpu="Non sélectionné.";
        String configuration = "CPU : "+cpu+"\n RAM : "+choixRam.getSelectedItem().toString()+"\n DD : "+choixDD.getSelectedItem().toString()+
                "\n Ecran : "+choixEcran.getSelectedItem().toString()+"\n Lecteur : "+choixLecteur.getSelectedItem().toString()+
                "\n Graveur : "+choixGraveur.getSelectedItem().toString();
        
        //On affiche dans une fenêtre d'information.s
        javax.swing.JOptionPane.showMessageDialog(this,configuration,"Configuration",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_Lancer

    private void Intel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Intel
        // Si le choix Intel est coché on récupère le texte.
        cpu = IntelPentium.getText();
    }//GEN-LAST:event_Intel

    private void AMD(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AMD
        // Si le choix AMD est coché on récupère le texte.
        cpu = AMD.getText();
    }//GEN-LAST:event_AMD

    private void Close(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close
        // On ferme l'application.
        dispose();
        java.lang.System.exit(0);
    }//GEN-LAST:event_Close

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoixConfiguration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoixConfiguration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoixConfiguration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoixConfiguration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoixConfiguration().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AMD;
    private javax.swing.JPanel CPU;
    private javax.swing.JRadioButton IntelPentium;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttonLancer;
    private javax.swing.JComboBox<String> choixDD;
    private javax.swing.JComboBox<String> choixEcran;
    private javax.swing.JComboBox<String> choixGraveur;
    private javax.swing.JComboBox<String> choixLecteur;
    private javax.swing.JComboBox<String> choixRam;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
    private String cpu;
    String [] listRam;
    String [] listDD;
    String [] listEcran;
    String [] listLecteur;
    String [] listGraveur;
}
